# Generated by Django 5.0 on 2023-12-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
